# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1392148802);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 184320);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140127194636");
user_pref("browser.slowStartup.averageTime", 2473);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage", "https://duckduckgo.com|http://partito-pirata.it");
user_pref("browser.startup.homepage_override.buildID", "20140127194636");
user_pref("browser.startup.homepage_override.mstone", "27.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1392234954092");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1392148554091");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 3679);
user_pref("datareporting.sessions.current.main", 1146);
user_pref("datareporting.sessions.current.sessionRestored", 3846);
user_pref("datareporting.sessions.current.startTime", "1392154201139");
user_pref("datareporting.sessions.current.totalTime", 17);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.0", "{\"s\":1392148551713,\"a\":4,\"t\":29,\"c\":true,\"m\":1000,\"fp\":3648,\"sr\":3883}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1392148681383,\"a\":20,\"t\":120,\"c\":true,\"m\":92,\"fp\":1094,\"sr\":1195}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1392148819051,\"a\":3,\"t\":14,\"c\":true,\"m\":62,\"fp\":980,\"sr\":1113}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:27.0");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"firebug@software.joehewitt.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/firebug@software.joehewitt.com\",\"mtime\":1392147192000,\"rdfTime\":1336149722000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/local/bin/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1392147907000,\"rdfTime\":1390889098000}}}]");
user_pref("extensions.lastAppVersion", "27.0");
user_pref("extensions.lastPlatformVersion", "27.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20140127194636");
user_pref("gecko.mstone", "27.0");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 6198);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1392154202);
user_pref("toolkit.telemetry.previousBuildID", "20140127194636");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1394740735);
